

test:
	../../Analysis/DifferentialExpression/prep_n_run_GOplot.pl --GO_annots data/Trinotate_report.xls.gene_ontology --DE_GO_enriched data/Trinity_genes.counts.matrix.log_growth_vs_heatshock.edgeR.DE_results.P0.001_C2.DE.subset.GOseq.enriched --DE_subset data/Trinity_genes.counts.matrix.log_growth_vs_heatshock.edgeR.DE_results.P0.001_C2.DE.subset --tmpdir . --pdf_filename goplot.pdf

clean:
	rm -f EC.david EC.genelist goplot.pdf

