

test:
	python2 ../../util/misc/TPM_weighted_gene_length.py --gene_trans_map Trinity.fasta.gene_trans_map --trans_lengths Trinity.fasta.seqlens --TPM_matrix rsem.isoform.TMM.EXPR.matrix
	python3 ../../util/misc/TPM_weighted_gene_length.py --gene_trans_map Trinity.fasta.gene_trans_map --trans_lengths Trinity.fasta.seqlens --TPM_matrix rsem.isoform.TMM.EXPR.matrix


clean:
